
var data = {
    list:[
        {"name":"李斌","company":"蔚来汽车","position":"创始人","address":"person/libin.png","href":"http://www.d1ev.com/news/renwu/44241"},
        {"name":"何小鹏","company":"小鹏汽车","position":"董事长","address":"person/hexiaopeng.png","href":"http://www.d1ev.com/kol/60078"},
        {"name":"沈晖","company":"威马汽车","position":"创始人董事长兼CEO","address":"person/shenhui.png","href":"http://www.d1ev.com/kol/59704"},
        {"name":"李想","company":"车和家","position":"创始人","address":"person/lixiang.png","href":"http://www.d1ev.com/kol/44096"},
        {"name":"郑刚","company":"北汽新能源","position":"总经理","address":"person/zhenggang.png","href":"http://www.d1ev.com/news/renwu/48014"},
        {"name":"刘心文","company":"云度新能源","position":"总经理","address":"person/liuxinwen.png","href":"http://www.d1ev.com/news/renwu/47565"},
        {"name":"鲍文光","company":"知豆电动汽车","position":"CEO","address":"person/baowenguang.png","href":"http://www.d1ev.com/carnews/yongche/38229"},
        {"name":"陆群","company":"前途汽车","position":"董事长","address":"person/luqun.png","href":"http://www.d1ev.com/news/renwu/53038"},
        {"name":"沈海寅","company":"奇点汽车","position":"创始人","address":"person/shenhaiyin.png","href":"http://www.d1ev.com/news/renwu/59962"},
        {"name":"付强","company":"爱驰亿维","position":"创始人","address":"person/fuqiang.png","href":"http://www.d1ev.com/tag/付强"},
        {"name":"朱江明","company":"零跑汽车","position":"董事长","address":"person/zhujiangming.png","href":"http://www.d1ev.com/tag/朱江明"},
        {"name":"曹忠","company":"长江汽车","position":"董事长","address":"person/caozhong.png","href":"http://www.d1ev.com/carnews/yongche/42775"},
        {"name":"王超","company":"开云汽车","position":"创始人","address":"person/wangchao.png","href":"http://www.d1ev.com/news/renwu/60118"},
        {"name":"陈峰","company":"时空电动","position":"董事长","address":"person/chenfeng.png","href":"http://www.d1ev.com/news/renwu/38227"},
        {"name":"张立平","company":"御捷汽车","position":"董事长","address":"person/zhangliping.png","href":"http://www.d1ev.com/tag/张立平"},
        {"name":"张海亮","company":"电咖汽车","position":"董事长","address":"person/zhanghailiang.png","href":"http://www.d1ev.com/tag/张海亮"}
    ],
    parters:[
        {"name":"云度新能源",address:"guests/yunduxinnengyuan.png"},
        {"name":"奇点汽车",address:"guests/qidianqiche.png"},
        {"name":"多氟多集团",address:"guests/duofuduo.png"},
        {"name":"华夏幸福",address:"guests/huaxiaxinfu.png"},
        {"name":"吉利新能源",address:"guests/jilixinnengyuan.png"},
        {"name":"小鹏汽车",address:"guests/xiaopengqiche.png"}
    ],
    medias:[
        {"name":"爱驰亿维",address:"guests/aichiyiwei.png"},
        {"name":"蔚来汽车",address:"guests/weilaiqiche.png"},
        {"name":"北汽新能源",address:"guests/beiqixinnegnyuan.png"},
        {"name":"奇瑞新能源",address:"guests/qiruixinnengyuan.png"},
        {"name":"江淮新能源",address:"guests/jianghuaxinnengyuan.png"},
        {"name":"开云汽车",address:"guests/kaiyunqiche.png"},
        {"name":"精进电动",address:"guests/jingjingdiandong.png"},
        {"name":"大郡控制",address:"guests/dajunkongzhi.png"}
    ],
    yehuaList:[
        {year:"2017","name":"春季夜话",address:"images/spring.png",link:"http://www.d1ev.com/news/qiye/51467"},
        {year:"2017","name":"夏季夜话",address:"images/2017summer.png",link:"http://www.d1ev.com/news/qiye/58418"},
        {year:"2017","name":"秋季夜话",address:"images/2017autumn.png",link:"javascript:;"},
        {year:"2016","name":"工程师夜话",address:"images/2016yehua.jpg",link:"http://d1ev.com/special/forumEngineer.html"}
    ],
    pic2015:{
        list:[
            {name:"pic1",address:"autoShowImages/2015-1.jpg"},
            {name:"pic2",address:"autoShowImages/2015-2.jpg"},
            {name:"pic3",address:"autoShowImages/2015-3.jpg"},
            {name:"pic4",address:"autoShowImages/2015-4.jpg"},
            {name:"pic5",address:"autoShowImages/2015-5.jpg"},
            {name:"pic6",address:"autoShowImages/2015-6.jpg"}
        ]
    },
    pic2016:{
        list:[
            {name:"pic1",address:"autoShowImages/2016-1.jpg"},
            {name:"pic2",address:"autoShowImages/2016-2.jpg"},
            {name:"pic3",address:"autoShowImages/2016-3.jpg"},
            {name:"pic4",address:"autoShowImages/2016-4.jpg"},
            {name:"pic5",address:"autoShowImages/2016-5.jpg"},
            {name:"pic6",address:"autoShowImages/2016-6.jpg"}
        ]
    },
    pic2017:{
        list:[
            {name:"pic1",address:"autoShowImages/2017-1.jpg"},
            {name:"pic2",address:"autoShowImages/2017-2.jpg"},
            {name:"pic3",address:"autoShowImages/2017-3.jpg"},
            {name:"pic4",address:"autoShowImages/2017-4.jpg"},
            {name:"pic5",address:"autoShowImages/2017-5.jpg"},
            {name:"pic6",address:"autoShowImages/2017-6.jpg"}
        ]
    }
}
